# fly.toml app configuration file generated for solitary-moon-656 on 2023-07-10T08:41:57-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "solitary-moon-656"
primary_region = "gru"
console_command = "/rails/bin/rails console"

[deploy]
  release_command = "./bin/rails db:prepare"

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
